quarkus:
  mongodb:
    connection-string: mongodb://mongo:27017

  oidc:
    auth-server-url: http://keycloak:8080/realms/QuarkusRealm
    roles:
      role-claim-path: resource_access/${quarkus.oidc.client-id}/roles

  smallrye-openapi:
    security-scheme: oauth2-implicit
    security-scheme-name: keycloak

swagger:
  oauth:
    authorization-url: http://localhost:8080/realms/QuarkusRealm/protocol/openid-connect/auth
