quarkus:
  http:
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated
        public:
          paths: /q/openapi,/q/openapi/*,/q/swagger-ui,/q/swagger-ui/*
          policy: permit
    port: 8081

  mongodb:
    database: BookstoreDb

  oidc:
    application-type: service
    client-id: quarkus-app
    tls:
      verification: none

  smallrye-openapi:
    security-scheme: oauth2-implicit
    security-scheme-name: keycloak

  swagger-ui:
    always-include: true
    oauth2-redirect-url: http://localhost:${quarkus.http.port}/q/swagger-ui/oauth2-redirect.html

mp:
  openapi:
    filter: org.quarkusmongodb.configs.SwaggerSecuritySchemeFilter